name: "Feature request"
description: Propose an enhanced or new capability
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
    - type: dropdown
    id: area
    attributes:
        label: Area
        options:
            - iOS
            - Crypto (E2EE)
            - Database (Supabase/Postgres)
            - Sync
            - CI/Tooling
            - Docs
            - Other
    validations:
        required: true
        
    - type: textarea
    id: problem
    attributes:
        label: Problem statement
        description: What pain or limitation are we addressing?
        placeholder: "Users can't restore keys easily when switching devices..."
    validations:
        required: true
        
    - type: textarea
    id: proposal
    attributes:
        label: Proposal
        description: What do you want to happen?
        placeholder: "Add recovery export/import with QR and file-based backup..."
    validations:
        required: true
        
    - type: textarea
    id: acceptance
    attributes:
        label: Acceptance criteria
        description: Define what "done" looks like.
        placeholder: |
            - Can export wrapped master key
            - Import works on a fresh install
            - Key material never logged
            - Unit tests added for envelope v1
    validations:
        required: true
        
    - type: textarea
    id: risks
    attributes:
        label: Risks / tradeoffs
        placeholder: "Increased complexity, user education needed, loss risk..."
    validations:
        required: false
        
    - type: dropdown
    id: priority
    attributes:
        label: Priority
        options:
            - P0 (blocker)
            - P1 (high)
            - P2 (medium)
            - P3 (low / nice-to-have)
    validations:
        required: true
        
